### ISSUE TITLE
nethvoice: set unified timezone value across all components

### ISSUE THREAD

**Issue by Stell0** [nethesis/ns8-nethvoice#120]
PRs:
 * https://github.com/nethesis/ns8-nethvoice/pull/143
 * https://github.com/nethesis/nethvoice-cti/pull/203
 * https://github.com/nethesis/nethvoice-cti/pull/204
 * https://github.com/nethesis/ns8-nethvoice/pull/147
 * https://github.com/nethesis/ns8-nethvoice/pull/149

**Comment by Amygos** [comment]
Waiting for release `0.0.8` of https://github.com/nethesis/nethvoice-cti  to close this issue.
