### ISSUE TITLE
ctiapp: validating NethVoice enterprise subscription for app activation

### ISSUE THREAD

**Issue by Amygos** [nethesis/ns8-nethvoice#125]
Validate if the Nethvoice mobile application is used for a Nethvoice instance with a valid Subscription.

PRs:
- https://github.com/nethesis/nethcti-server/pull/305
- https://github.com/nethesis/nethinfra/pull/199
- https://github.com/nethesis/ns8-nethvoice/pull/146
- https://github.com/nethesis/ctiapp-authproxy/pull/6
- https://github.com/nethesis/nethvoice-cti/pull/208
- https://github.com/nethesis/nethcti-server/pull/306

**Comment by Stell0** [comment]
Before merging https://github.com/nethesis/ctiapp-authproxy/pull/6 we need to backport https://github.com/nethesis/nethcti-server/pull/305 to nethcti-server on NS 7
