### ISSUE TITLE
nethvoice: add proxy configuration for gateway and physical trunks

### ISSUE THREAD

**Issue by Amygos** [nethesis/ns8-nethvoice#128]
- Add proxy in gateway and physical trunks configuration
- remove all provisioning functions, the configuration will be only uploaded manually

PRs:
* https://github.com/nethesis/nethvoice-wizard-restapi/pull/227
* https://github.com/nethesis/ns8-nethvoice/pull/142
* https://github.com/nethesis/nethvoice-wizard-ui/pull/190
* https://github.com/nethesis/nethvoice-wizard-ui/pull/194

**Comment by Stell0** [comment]
Implemented not tested:

Patton
- [ ] 4112fxo
- [ ] 4112fxs
- [ ] 4114fxo
- [ ] 4114fxs_fxo
- [ ] 4114fxs
- [ ] 4116fxs4_fxo2
- [ ] 4118fxs_fxo
- [ ] 4118fxs
- [ ] 4526fxs
- [ ] 4552
- [ ] 4554
- [ ] 4638
- [ ] 4661fxs2_fxo2_isdn2
- [ ] 4661fxs4_fxo4_isdn4
- [ ] 4661fxs4_isdn2
- [ ] 4661fxs4_isdn4
- [ ] 4661fxs4_isdn8
- [ ] 4661
- [ ] 4671fxs8_isdn4
- [ ] 4970_4
- [ ] 4970

Grandstream
- [ ] gxw4216TLS
- [ ] gxw4216
- [ ] gxw4224TLS
- [ ] gxw4224
- [ ] gxw4232TLS
- [ ] gxw4232
- [ ] gxw4248TLS
- [ ] gxw4248
- [ ] ht801TLS
- [ ] ht801
- [ ] ht802TLS
- [ ] ht802
- [ ] ht812TLS
- [ ] ht812
- [ ] ht814TLS
- [ ] ht814
