### ISSUE TITLE
nethvoice: change CTI API endpoint

### ISSUE THREAD

**Issue by Amygos** [nethesis/ns8-nethvoice#152]
CTI API endpoint is $NETHVOICE_HOST, but it's difficult for the user that have to enter it in nethlink configuration. Fix is to use cti url instead of nethvoice url as nethcti api endpoint

- [x]  change API_ENDPOINT in nethcti-ui container unit
- [x] change traefik routes for nethcti-server and websocket

PR:
* https://github.com/nethesis/ns8-nethvoice/pull/153

**Comment by Stell0** [comment]
make sure that the wizard dashbord doesn't break: it makes requests to [/webrest ](https://github.com/nethesis/nethvoice-wizard-ui/blob/42d77cf0979a4c92ab6e423e3281b3e1353b82a4/root/etc/e-smith/templates/var/www/html/freepbx/wizard/scripts/custom.js/10base#L15)
