### ISSUE TITLE
nethvoice: regenerate tancredi defaults

### ISSUE THREAD

**Issue by Amygos** [nethesis/ns8-nethvoice#157]
Right now, the tancredi''s defaults are written only at the first start of the container

Relevant code: https://github.com/nethesis/ns8-nethvoice/blob/e83c02ed48246dc13a8ac52e18bf7618a69d2771/tancredi/entrypoint.sh#L48

This can cause some problems, like:
If NethVoice is configured before the proxy, the value of the default proxy's domain is stored in the tancredi's defaults, it is a random domain and there is no easy way to change it.

PRs:
- [x] https://github.com/nethesis/ns8-nethvoice/pull/162
- [x]  https://github.com/nethesis/ns8-nethvoice/pull/168
- [ ] https://github.com/nethesis/ns8-nethvoice/pull/169

**Comment by Stell0** [comment]
Some default options needs to be removed from interface:

Encryption (should be always enabled)
PBX address
Timezone
all LDAP configuration

![Screenshot from 2024-03-14 17-51-18](https://github.com/nethesis/ns8-nethvoice/assets/4547897/88614a50-7086-4558-bf8f-9091dbf8440b)
