### ISSUE TITLE
NethVoice community version: user limit

### ISSUE THREAD

**Issue by Stell0** [nethesis/ns8-nethvoice#205]
Add limit to 8 users in NethVoice interface on a community version

PR:
https://github.com/nethesis/ns8-nethvoice/pull/206

**Comment by Stell0** [comment]
the post /mainextensions API now returns `403` `{"status":"ERROR: community version is limited to 8 users"}` if it isn't an enterprise version. 

Error still needs to be displayed to the user

**Comment by compgeniuses** [comment]
Hello, Apologies for inquiring on this here. Will the License Required be a Nethvoice License or Nethserver License

**Comment by andrea-marchionni** [comment]
> Hello, Apologies for inquiring on this here. Will the License Required be a Nethvoice License or Nethserver License

The license required will be a NethVoice License, soon a post on the community forum will explain all the details.
