### ISSUE TITLE
nethvoice: test freepbx user domain change

### ISSUE THREAD

**Issue by Amygos** [nethesis/ns8-nethvoice#211]
Test the behavior of a change of the users' domain **after** the  first `configure-module`

**Comment by Stell0** [comment]
when user domain is changed
- new users are saved into `userman_users` table.
- rest_devices_phones table isn't changed
- rest_users isn't touched
- extensions aren't removed

there are three possible solutions, all requires some coding:
- Prevent the user domain change (requires work on the interface and documentation)
- Delete everything when changing (a warning on the interface would be appropriate)
- Delete everything and save the state to allow reverting to the old user provider (requires some coding and extensive testing)
