### ISSUE TITLE
nethvoice, nethvoice-proxy: Don't use NS8's default environment for sensitive data

### ISSUE THREAD

**Issue by Amygos** [nethesis/ns8-nethvoice#261]
Environment variables written using agent.set_env() are stored in NS8 Redis and are readable by everyone. We need to avoid to use agent.set_env() for sensitive variables.

One Proposed solution is to write configuration to a json file, backup it, and write configuration to environment on module configure.
Another solution is to use core functions [read_envfile](https://github.com/NethServer/ns8-core/blob/ce3ffde4377c7663cf8fb703404fe4c919c67d40/core/imageroot/usr/local/agent/pypkg/agent/__init__.py#L87)/[write_envfile](https://github.com/NethServer/ns8-core/blob/ce3ffde4377c7663cf8fb703404fe4c919c67d40/core/imageroot/usr/local/agent/pypkg/agent/__init__.py#L108), to store sensitive variables.

Implementing this will probably cause regressions in installation, backup and restore, migration from 7 and move/clone from node to node.

Actions to modify:
- [ ] `create-module`
- [ ] `update-module`
- [ ] `import-module`
- [ ] `transfert-state`
- [ ] `clone-module`
- [ ] `restore-module`

**Comment by andrea-marchionni** [comment]
Dupicate of https://github.com/NethServer/dev/issues/7011
