### ISSUE TITLE
nethvoice: missing costumer card  templates

### ISSUE THREAD

**Issue by Amygos** [nethesis/ns8-nethvoice#263]
The customer card templates are stored in the `/var/lib/nethserver/nethcti/templates/customer_card/` directory and must be shared between `freepbx` and `nethcti-server`. The uploaded custom templates must be persistent.

The directory is not shared, and the changes are not preserved.

To fix this issue:
* Create a shared volume for the customer cards.
* Copy the custom customer cards when migrating from NS7 to NS8.

Prs:

* https://github.com/nethesis/ns8-nethvoice/pull/265
* https://github.com/NethServer/nethserver-ns8-migration/pull/75

**Comment by Stell0** [comment]
How to test:
1.
- install nethserver-ns8-migration from testing repoository
- enable testing repository on ns8
- install ns8-nethvoice-proxy on ns8
- migrate
- check if customer cards are present

2. 
- install nethserver-ns8-migration from testing repoository
- make sure testing repository on ns8 is disabled
- install ns8-nethvoice-proxy on ns8
- migrate
- enable testing repository on ns8
- update ns8-nethvoice
- check if customer cards are present
