### ISSUE TITLE
Incorrect display of calls answered by the queue in the history

### ISSUE THREAD

**Issue by mgarra** [nethesis/ns8-nethvoice#283]
**Describe the bug**
Calls coming from a queue and answered are reported twice in the history, once corrected as answered and once as not answered

**To Reproduce**
1. Answer a call coming from a queue
2. After closing, check in the history how it is reported

**Screenshots**
![image](https://github.com/user-attachments/assets/77c6a67e-1d7f-42f7-b035-3d289b3ddb51)

**Additional context**
If the call is answered by NethLink it sends the missed call notification as soon as it is closed

**Comment by andrea-marchionni** [comment]
dup of https://github.com/NethServer/dev/issues/7015
