### ISSUE TITLE
Nethvoice UI: Ensure Proxy Installation Check

### ISSUE THREAD

**Issue by stephdl** [nethesis/ns8-nethvoice#319]
When installing Nethvoice, the initial step is to navigate to the application settings, configure the necessary hostnames, and press the Save button. However, Nethvoice cannot function without the proxy, and during the "Configure Module" action, the system checks if the proxy is installed. If the proxy is not present, the UI throws an unclear error.

**Proposed solution**

The UI should check if the proxy is installed and configured before allowing the user to begin the configuration process. This would prevent confusion and ensure a smoother setup experience.

**Alternative solutions**

do nothing

**Additional context**

nethvoice:1.0.2

**See also**

see https://mattermost.nethesis.it/nethesis/pl/rwbc11p34tdz8q36cqugeqo83c

**Comment by Amygos** [comment]
Wrong issue tracker, please reopen the issue here: https://github.com/NethServer/dev/issues

**Comment by stephdl** [comment]
closed by https://github.com/NethServer/dev/issues/7057
