### ISSUE TITLE
https://NETHVOICE_HOST/nethvoice wrong redirect

### ISSUE THREAD

**Issue by Stell0** [nethesis/ns8-nethvoice#40]
https://NETHVOICE_HOST/nethvoice redirects to https://NETHVOICE_HOST:PORT/nethvoice and doesn't work
https://NETHVOICE_HOST/nethvoice/ works correctly

(it's the slash at the end of the path)

**Comment by gsanchietti** [comment]
See also https://github.com/orgs/nethesis/projects/7/views/1?pane=issue&itemId=24439847

Please note that  '/freepbx` has the same problem.

**Comment by Stell0** [comment]
Issue stil present
