### ISSUE TITLE
Wizard: setup conference jitsi url

### ISSUE THREAD

**Issue by Amygos** [nethesis/ns8-nethvoice#69]
- [ ] nethvoice-wizard-restapi: store jitsi conference url into mysql
- [ ] nethcti3freepx: create /etc/nethcti/video_conf.json with jitsi url
- [ ] nethvoice-wizard-ui hide jitsi conference url settings
- [ ] remove CONFERENCE_JITSI_URL environment

---

![Image](https://user-images.githubusercontent.com/804596/229047229-d3d83f33-24ae-4987-9743-92feaa057da0.png)

**Comment by Stell0** [comment]
- [ ] nethvoice-wizard-restapi: store jitsi conference url into mysql
- [ ] nethcti3freepx: create /etc/nethcti/video_conf.json with jitsi url
- [ ] nethvoice-wizard-ui hide jitsi conference url settings
- [ ] remove CONFERENCE_JITSI_URL environment

**Comment by Amygos** [comment]
Moved to https://github.com/orgs/NethServer/projects/11/views/1?pane=issue&itemId=79592275
