### ISSUE TITLE
NS7 migration

### ISSUE THREAD

**Issue by Amygos** [nethesis/ns8-nethvoice#70]
Implement migration from NS7 to NS8
- [ ] https://github.com/NethServer/nethserver-ns8-migration/pull/50
- [ ] https://github.com/nethesis/ns8-nethvoice/pull/91

**Comment by Stell0** [comment]
Problems to solve:
- [ ] phonebook db isn't migrated
- [ ] tancredi files has wrong user/group
- [ ] nethcti-server fails to start
- [ ] nethcti-server isn't automatically started

**Comment by Stell0** [comment]
TODO:
- [ ] start nethcti-server with a step at the end of import-module action
- [ ] load CDR data in a separate step so it doesn't block the startup
