### ISSUE TITLE
push notification

### ISSUE THREAD

**Issue by Stell0** [nethesis/ns8-nethvoice#76]
- [ ] Kamailio should call script on right freepbx instance, by either calling it on http://127.0.0.1:INSTANCE_PORT/push-proxy or https://INSTANCE_HOST/push-proxy. The first one is preferred 
- [ ] fix script (take subscription key and secret from environment, etc...)

https://github.com/nethesis/ns8-nethvoice-proxy/pull/6

**Comment by andrea-marchionni** [comment]
I think with the new mobile app it is no longer necessary @Amygos @Stell0
