### ISSUE TITLE
nethvoice: Fix "Advanced" link  in nethvoice wizard

### ISSUE THREAD

**Issue by Amygos** [nethesis/ns8-nethvoice#93]
When advanced link in nethvoice wizard is clicked, you are redirected to `http://HOST:PORT/freepbx...` instead of `https://HOST/freepbx...`

Example: https://community.nethserver.org/t/ns8rc1-martin-my-experiences-and-findings-breaking-things-as-a-user-and-suggestions-for-improvements/22515/3

**Comment by edospadoni** [comment]
Fix in this commit: https://github.com/nethesis/nethvoice-wizard-ui/commit/0598ff66cf76ed548868b9465fb20edfab1ac524#diff-bc1112096acb7fa9a90f4b2304513b6da6bbdd60d124576434bf393a6ff97eb1R298
